#!usr/bin/env python3
#Made by Maximiliano Fairman
#Created on oct 10th 2025
#this program is a trapezoidal prism volume and surface area calculator

#Greeting when started
print("Hello user!")
print("This program is a calculator for trapezoidal prisms.")
print("Specifically volume and surface area")
print("")

# Get user input
topbase = float(input("Input Top base (b1) (cm): "))
bottombase = float(input("Input Bottom base (b2) (cm): "))
height = float(input("Input Height of trapezoid (h) (cm): "))
slant1and2 = float(input("Input slant side 1 and 2 (s1) (cm): "))
length = float(input("Input Length of the prism (cm): "))

# Calculate base area
base_area = 0.5 * (topbase + bottombase) * height

# Calculate volume
volume = base_area * length

# Calculate surface area
surface_area = 2 * base_area + (topbase + bottombase + slant1and2) * length

# Display answers
print("Volume: cm", volume)
print("Surface Area: cm", surface_area)

# Tell user when finished
print("This program has finished.")
